name: 'Setup K8s Istio'
description: 'This action setup Istio on K8s'
author: 'JaSiLez'
branding:
  icon: anchor
  color: blue
inputs:
  istio_version:
    description: 'Istio version to install'
    required: false
    default: '1.9.3'
  kubeconfig:
    description: 'Content of ~/.kube/config'
    required: true
  # istio_args:
  #   description: "Istio install parameters"
  #   required: false
  #   default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'